In [5]:
import joblib
from sklearn.datasets import fetch_california_housing

In [6]:
X,y=fetch_california_housing(return_X_y=True)
model=joblib.load('linear_model.pkl')
transormer=joblib.load('transformer.pkl')

In [8]:
data=X[0]

In [9]:
transformed_data=transormer.transform(data)

ValueError: Expected 2D array, got 1D array instead:
array=[   8.3252       41.            6.98412698    1.02380952  322.
    2.55555556   37.88       -122.23      ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [13]:
# ValueError: Expected 2D array, got 1D array instead:
# array=[   8.3252       41.            6.98412698    1.02380952  322.
#     2.55555556   37.88       -122.23      ].
# Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
# to fix the above error, we need to reshape the data to be 2d
data=data.reshape(1,-1)

In [14]:
data.shape

(1, 8)

In [15]:
transformed_data=transormer.transform(data)

In [16]:
transformed_data

array([[ 1.00000000e+00,  8.32520000e+00,  4.10000000e+01,
         6.98412698e+00,  1.02380952e+00,  3.22000000e+02,
         2.55555556e+00,  3.78800000e+01, -1.22230000e+02,
         6.93089550e+01,  3.41333200e+02,  5.81442540e+01,
         8.52341905e+00,  2.68071440e+03,  2.12755111e+01,
         3.15358576e+02, -1.01758920e+03,  1.68100000e+03,
         2.86349206e+02,  4.19761905e+01,  1.32020000e+04,
         1.04777778e+02,  1.55308000e+03, -5.01143000e+03,
         4.87780297e+01,  7.15041572e+00,  2.24888889e+03,
         1.78483245e+01,  2.64558730e+02, -8.53669841e+02,
         1.04818594e+00,  3.29666667e+02,  2.61640212e+00,
         3.87819048e+01, -1.25140238e+02,  1.03684000e+05,
         8.22888889e+02,  1.21973600e+04, -3.93580600e+04,
         6.53086420e+00,  9.68044444e+01, -3.12365556e+02,
         1.43489440e+03, -4.63007240e+03,  1.49401729e+04]])

In [17]:
model.predict(transformed_data)

array([4.07722554])

In [18]:
# to save all the steps and model

np.float64(4.526)

In [19]:
# load_pipe
pipe=joblib.load('pipe.pkl')

In [20]:
pipe

Pipeline(steps=[('polynomial_transformer', PolynomialFeatures()),
                ('model', LinearRegression())])

In [21]:
pipe.predict(data)

array([4.07722554])