In [8]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
import seaborn as sb
import scipy.stats as st
import joblib

In [2]:
X,y=fetch_california_housing(return_X_y=True)

In [3]:
transformer=PolynomialFeatures()

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [5]:
ply_X=transformer.fit_transform(X_train)

In [6]:
lr=LinearRegression()

In [7]:
lr.fit(ply_X,y_train)

LinearRegression()

In [52]:
X_test_ply=transformer.transform(X_test)

In [51]:
y_train.shape

(15480,)

In [53]:
X_test_ply.shape

(5160, 45)

In [54]:
lr.predict(X_test_ply)

array([2.02019515, 1.94176804, 1.1369122 , ..., 2.29268222, 2.26758099,
       2.78191362])

In [55]:
transformer.get_feature_names_out()

array(['1', 'x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x0^2',
       'x0 x1', 'x0 x2', 'x0 x3', 'x0 x4', 'x0 x5', 'x0 x6', 'x0 x7',
       'x1^2', 'x1 x2', 'x1 x3', 'x1 x4', 'x1 x5', 'x1 x6', 'x1 x7',
       'x2^2', 'x2 x3', 'x2 x4', 'x2 x5', 'x2 x6', 'x2 x7', 'x3^2',
       'x3 x4', 'x3 x5', 'x3 x6', 'x3 x7', 'x4^2', 'x4 x5', 'x4 x6',
       'x4 x7', 'x5^2', 'x5 x6', 'x5 x7', 'x6^2', 'x6 x7', 'x7^2'],
      dtype=object)

In [87]:
ls=Lasso(alpha=.5)#L1
rg=Ridge(alpha=.6)#L2

In [88]:
ls.fit(ply_X,y_train)
ls.score(X_test_ply,y_test)

C:\Users\HP Zbook Fury 15 G7\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.669e+03, tolerance: 2.055e+00
  model = cd_fast.enet_coordinate_descent(


-0.016971311249831755

In [82]:
rg.fit(X_train,y_train)
rg.score(X_test,y_test)

0.5988002200447061

0.4498374530843182

0.5988012905801887

In [64]:
lr2=LinearRegression()
lr2.fit(X_train,y_train)
lr2.score(X_test,y_test)

0.5987985841521111

# Lasso and Ridge

In [6]:
ls=Lasso()
ls.fit(X_train,y_train)
ls.coef_

array([ 1.50331238e-01,  6.05794356e-03,  0.00000000e+00, -0.00000000e+00,
       -6.16592406e-06, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [7]:
rid=Ridge()
rid.fit(X_train,y_train)
rid.coef_

array([ 4.44222630e-01,  9.66366044e-03, -1.17613930e-01,  7.33832242e-01,
       -3.62354123e-06, -3.47123667e-03, -4.20749222e-01, -4.35599935e-01])

In [9]:
en=ElasticNet()
en.fit(X_train,y_train)
en.coef_

array([ 2.56286763e-01,  1.15338585e-02,  0.00000000e+00, -0.00000000e+00,
        8.47331574e-06, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [14]:
weights=np.random.random(size=(8,1))
bias=-.5

In [15]:
y_hat=X_train.dot(weights)+bias

In [16]:
y_hat

array([[ 474.51181373],
       [1268.9919854 ],
       [ 630.42142499],
       ...,
       [ 800.56829595],
       [1333.58991632],
       [ 906.5806369 ]])

In [20]:
np.sum((y_train-y_hat)**2)/X_train.shape[0]

np.float64(35466881120.998726)

In [26]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [27]:
sigmoid(35466881120.998726)

np.float64(1.0)

In [30]:
np.log(0)

C:\Users\HP Zbook Fury 15 G7\AppData\Local\Temp\ipykernel_3092\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


np.float64(-inf)

In [11]:
import joblib

In [12]:
joblib.,

TypeError: file must have a 'write' attribute

In [10]:
with open('model',mode='xb') as m:
    m.write(lr)

TypeError: a bytes-like object is required, not 'LinearRegression'

# Model Saving

In [10]:
joblib.dump(lr,"linear_model.pkl")

['linear_model.pkl']

In [11]:
joblib.dump(transformer,"transformer.pkl")

['transformer.pkl']

In [14]:
# We can save the steps (all transformations i.e. polynomial features)
# and model in one file by using pipelines

In [15]:
from sklearn.pipeline import Pipeline

In [23]:
pipe=Pipeline([('polynomial_transformer',PolynomialFeatures())
               ,('model',LinearRegression())])

In [24]:
pipe

Pipeline(steps=[('polynomial_transformer', PolynomialFeatures()),
                ('model', LinearRegression())])

In [25]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('polynomial_transformer', PolynomialFeatures()),
                ('model', LinearRegression())])

In [26]:
joblib.dump(pipe,'pipe.pkl')

['pipe.pkl']