In [47]:
import numpy as np
from scipy.sparse import csr_matrix,csc_matrix

In [2]:
m=list(range(1,25))

In [4]:
ar=np.array(m)

In [6]:
print(ar.ndim)
print(ar.shape)

1
(24,)


In [11]:
c=ar.reshape((6,4))

In [39]:
a=np.ones((3,4),dtype=int)

In [40]:
a.dtype

dtype('int64')

In [27]:
ar.reshape((2,4,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
m2=np.array(list(range(1,785)))

In [21]:
ar2=m2.reshape((28,-1))

In [23]:
ar2.shape

(28, 28)

In [49]:
#arange
f=np.arange(9).reshape(3,3)

In [52]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [57]:
np.random.random((3,3)).size

9

In [58]:
np.savez('dsfdsfds.npz',ones=ar)

In [61]:
with np.load('dsfdsfds.npz') as f:
    g=f['ones']
g

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [6]:

s="this is a random text"

file=open('file.txt','a')
file.close()

In [21]:
with open("file.txt") as h:
    # h.write('\n')
    print(h.readlines())

['jghjkljhjkl;ljhk\n', 'hjkljhjkl;.l\n', ';lkjhghjkl;lk']


In [39]:
a=np.random.randint(low=1,high=10,size=(3,3))
b=np.random.randint(low=11,high=20,size=(3,3))

In [40]:
vertical=np.vstack((a,b))

In [41]:
horizontal=np.hstack((a,b))

In [42]:
horizontal

array([[ 9,  3,  9, 14, 17, 15],
       [ 4,  2,  2, 11, 11, 12],
       [ 2,  8,  8, 14, 14, 16]], dtype=int32)

In [43]:
z=np.zeros((2,3))

In [45]:
z[0,1]=5

In [46]:
z

array([[0., 5., 0.],
       [0., 0., 0.]])

In [48]:
a=np.array([[1,0,0,1,0,0],
            [0,0,2,0,0,1]])

In [49]:
mat=csr_matrix(a)

In [51]:
print(mat)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (2, 6)>
  Coords	Values
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1


In [54]:
x=mat.todense()

In [56]:
x[x>0]

matrix([[1, 1, 2, 1]])

In [58]:
mat

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (2, 6)>