In [1]:
import numpy as np

In [2]:
m=list(range(1,25))

In [4]:
ar=np.array(m)

In [6]:
print(ar.ndim)
print(ar.shape)

1
(24,)


In [11]:
c=ar.reshape((6,4))

In [39]:
a=np.ones((3,4),dtype=int)

In [40]:
a.dtype

dtype('int64')

In [27]:
ar.reshape((2,4,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
m2=np.array(list(range(1,785)))

In [21]:
ar2=m2.reshape((28,-1))

In [23]:
ar2.shape

(28, 28)

In [49]:
#arange
f=np.arange(9).reshape(3,3)

In [52]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [57]:
np.random.random((3,3)).size

9

In [58]:
np.savez('dsfdsfds.npz',ones=ar)

In [61]:
with np.load('dsfdsfds.npz') as f:
    g=f['ones']
g

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])